# from perplexity

from confluent_kafka import DeserializingConsumer
from confluent_kafka.schema_registry import SchemaRegistryClient
from confluent_kafka.schema_registry.protobuf import ProtobufDeserializer
from confluent_kafka.serialization import StringDeserializer

from my_proto_pb2 import User  # generated by protoc

schema_registry_conf = {
    "url": "https://<schema-registry-url>",
    "basic.auth.user.info": "<api-key>:<api-secret>",
    "basic.auth.credentials.source": "USER_INFO",
}

schema_registry_client = SchemaRegistryClient(schema_registry_conf)

protobuf_deserializer = ProtobufDeserializer(
    User,
    schema_registry_client,
    conf={"use.deprecated.format": False}
)

consumer_conf = {
    "bootstrap.servers": "<broker>",
    "group.id": "my-group",
    "key.deserializer": StringDeserializer("utf_8"),
    "value.deserializer": protobuf_deserializer,
    "auto.offset.reset": "earliest",
}

consumer = DeserializingConsumer(consumer_conf)
consumer.subscribe(["my-topic"])

while True:
    msg = consumer.poll(1.0)
    if msg is None:
        continue

    key = msg.key()     # str
    value = msg.value() # User protobuf object
    print(f"User id={value.id}, name={value.name}")
