# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x0b\x63lickstream\"\xa7\x01\n\x06\x65vents\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0e\n\x06userid\x18\x02 \x01(\x05\x12\x13\n\x0bremote_user\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\x12\r\n\x05_time\x18\x05 \x01(\x03\x12\x0f\n\x07request\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\r\n\x05\x62ytes\x18\x08 \x01(\t\x12\x10\n\x08referrer\x18\t \x01(\t\x12\r\n\x05\x61gent\x18\n \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTS']._serialized_start=30
  _globals['_EVENTS']._serialized_end=197
# @@protoc_insertion_point(module_scope)
